source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               libs/FPcore.jar,\
               OSGI-INF/ro.linic.ui.pos.driver.zfplab.services.impl.ZFPLabECRDriver.xml,\
               plugin.xml,\
               OSGI-INF/l10n/
