source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               icons/,\
               OSGI-INF/ro.linic.ui.base.services.impl.DataServicesImpl.xml,\
               libs/jnats-2.25.2.jar,\
               OSGI-INF/ro.linic.ui.base.services.impl.MessagingServiceImpl.xml
